In [186]:
import numpy as np
np.random.seed(seed=0)

# DataType & Attributes

In [187]:
# numpy's main datatype is ndarray (n-dimentional array)

In [188]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [189]:
a2 = np.array([[1,2.5],[3,4]])
a2

array([[1. , 2.5],
       [3. , 4. ]])

In [190]:
a3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
a3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [191]:
a1.shape

(4,)

In [192]:
a1.ndim

1

In [193]:
a2.ndim

2

In [194]:
a3.ndim

3

In [195]:
a1.dtype

dtype('int64')

In [196]:
a2.dtype

dtype('float64')

In [197]:
a1.size

4

In [198]:
a2.size

4

In [199]:
a3.size

12

In [200]:
# create pandas dataframe from np array

In [201]:
import pandas as pd

df = pd.DataFrame(a2)
df

0    1
0  1.0  2.5
1  3.0  4.0

## Creating NumPy arrays

In [202]:
ones = np.ones((2,2),dtype=int)
ones

array([[1, 1],
       [1, 1]])

In [203]:
zeros = np.zeros((2,2))
zeros

array([[0., 0.],
       [0., 0.]])

In [204]:
random_array = np.random.randint(0,10,(5))
random_array

array([5, 0, 3, 3, 7])

In [205]:
random_array2 = np.random.random((5,3))
random_array2

array([[0.4236548 , 0.64589411, 0.43758721],
       [0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675]])

In [206]:
random_array3 = np.random.rand(5,3)
random_array3

array([[0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443],
       [0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561],
       [0.77423369, 0.45615033, 0.56843395]])

In [207]:
# Viewing np arrays

In [208]:
print(np.unique(random_array,return_counts=True))

(array([0, 3, 5, 7]), array([1, 2, 1, 1]))
